### ISSUE TITLE
[NOT AN ISSUE] -Simple double range slider

### ISSUE THREAD

**Issue by kuatroka** [janosh/svelte-zoo#11]
Love your work, thanks for that! 

I was wondering if you might already have a double range slider component somewhere that is just not included in this library. 

An example could be a double range slider with a list of years from 2000 to 2020, and I would be able to select data that only between 2010 to 2015.
Thanks

**Comment by janosh** [comment]
Thanks for the kind words! There are existing Svelte packages with such a component. Both of these should serve your purpose:

- https://github.com/simeydotme/svelte-range-slider-pips
- https://mhkeller.com/svelte-double-range-slider

**Comment by kuatroka** [comment]
Thanks Janosh.
